platform :ios, '13.0'

target "IBigRise" do
     pod 'NIMSDK_LITE', '9.16.5'
     pod 'TZImagePickerController'
     pod 'IQKeyboardManager'
     pod 'SDWebImage'
     pod 'SDWebImageFLPlugin'
     pod 'Toast'
     pod 'YYImage'
     pod 'YYImage/WebP'
     pod 'AFNetworking', :git => 'https://github.com/NewAFNetworking/AFNetworking.git'
     pod 'Masonry'
     pod 'YYText'
     pod 'FFDropDownMenu'
     pod 'TXScrollLabelView'
     pod 'FMDB'
     pod 'Reachability'
     pod 'SVProgressHUD'
     pod 'YYModel'
     pod 'UCZProgressView'
     pod 'FLAnimatedImage'
     pod 'LEEAlert'
     pod 'MJExtension'
     pod 'SSZipArchive'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['COMPILER_INDEX_STORE_ENABLE'] = 'NO'
    end
  end
end

